import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import {Toaster} from "sonner"
import ChatBot from "@/components/chatbot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Healthcare System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <ChatBot 
            appId="203cd051746a89a514049244c9cf1fcda" 
            popupWidget={true} // Hiển thị nút bật chat
            automaticChatOpenOnNavigation={true} // Tự động mở chat
          />
        <Toaster richColors position ='top-center'></Toaster>
      </body>
    </html>

    </ClerkProvider>
    
  );
}
